### PR TITLE
Support org.freedesktop.FileManager1 interface

### LINKED ISSUE #98: Implement org.freedesktop.FileManager1 service
See https://www.freedesktop.org/wiki/Specifications/file-manager-interface/

### PR DESCRIPTION
**Pull request by tchx84**
Closes #98

### CODE REVIEW

**Comment by tchx84** [comment]
hey @henry-nicolas ! could you run your packaging linters on this branch? To make sure I am not missing something.

**Comment by henry-nicolas** [comment]
Hello @tchx84 , just checked, it raised one message: https://paste.debian.net/1184761/

Basically, it relates to the name used inside the .service file which is advised to be set to the same name as the .service file is called, helping avoid duplicates.

**Comment by tchx84** [comment]
> Hello @tchx84 , just checked, it raised one message: https://paste.debian.net/1184761/
> 
> Basically, it relates to the name used inside the .service file which is advised to be set to the same name as the .service file is called, helping avoid duplicates.

Hmm, I see, I can easily rename it but... the reason I renamed it is because Nautilus provides the exact same file (and path)... because this D-bus interface is a freedesktop "standard".

Any suggestion?

**Comment by henry-nicolas** [comment]
Yes, I think this make sense, the name indeed appears to be a standard and one can't set the filename to this value else we would have conflcts between file managers.

Example 1 : Nautilus provides both .service files (one specific to package name and one with freedesktop standard): https://paste.debian.net/1184769/
Example 2 : Nemo, as you mentionned, ships a file which filename is different from the DBUS interface name (which makes sense else I could not install both Nemo and Nautilus): https://paste.debian.net/1184771/

I wil just overwrite this lintian message, I think we are all good here :-)

**Comment by tchx84** [comment]
> Yes, I think this make sense, the name indeed appears to be a standard and one can't set the filename to this value else we would have conflcts between file managers.
> 
> Example 1 : Nautilus provides both .service files (one specific to package name and one with freedesktop standard): https://paste.debian.net/1184769/
> Example 2 : Nemo, as you mentionned, ships a file which filename is different from the DBUS interface name (which makes sense else I could not install both Nemo and Nautilus): https://paste.debian.net/1184771/
> 
> I wil just overwrite this lintian message, I think we are all good here :-)

Awesome! thanks for the checking!

**Pull request merged**
