### PR TITLE
Support i18n

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@AsciiWolf @ovari @Vistaus @eson57 @cho2 @MiloCasagrande @stenosis in case you're interested in mobile ;)

**Comment by Vistaus** [comment]
@tchx84 Why, of course! I'll dive right into it! 🙂

**Comment by eson57** [comment]
Of course I can help translate, even though it doesn't look very suitable to Sailfish OS, which is my daily drive.   ;)

**Comment by AsciiWolf** [comment]
I'll see if I get some free time in upcoming weeks. ;-)

**Pull request merged**
