### PR TITLE
Add screen to display file properties

### LINKED ISSUE #102: Show file properties view
I recently implemented file manager interface but, the `ShowItemProperties` requires an actual UI to display these. This requires design as to how these properly screen should and look and how it should show.

From [1] :

> ShowItemProperties should cause the file manager to show a "properties" window for the specified URIs. For local Unix files, these properties can be the file permissions, icon used for the files, and other metadata.

[1] https://www.freedesktop.org/wiki/Specifications/file-manager-interface/

### PR DESCRIPTION
**Pull request by tchx84**
Closes #102

### CODE REVIEW

**Comment by tchx84** [comment]
Peek 2021-02-15 18-14

@bertob since is how is working / looking so far, in case you have the time for feedback.

**Comment by bertob** [comment]
We're not really using the old table-style list layouts anymore, a listbox would be better here.

**Comment by tchx84** [comment]
> We're not really using the old table-style list layouts anymore, a listbox would be better here.

aha! any good example out there I can use for reference?

**Comment by bertob** [comment]
> EDIT: or you mean something like we do in Flatseal, except there's no activable options?

Pretty much, yeah.

In terms of layout it'd be basically like some of the listboxes in the about panel in Settings (though the listbox would have the new rounded styling):

image

**Comment by tchx84** [comment]
> > EDIT: or you mean something like we do in Flatseal, except there's no activable options?
> 
> Pretty much, yeah.
> 
> In terms of layout it'd be basically like some of the listboxes in the about panel in Settings (though the listbox would have the new rounded styling):
> 
> image

Oh yes! much better, will do that. Thanks!

**Comment by tchx84** [comment]
@bertob yup, definitely better :)

image

**Pull request merged**
