### PR TITLE
data: Add polkit rules for udisk2

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@henry-nicolas @craftyguy @Danct12 in case you have the time to test this on your distros ;)

**Comment by henry-nicolas** [comment]
Thanks for the heads-up @tchx84, I will test it this week-end

**Review by henry-nicolas — APPROVED** [review]
LGTM - tested on a Debian system successfuly

**Comment by tchx84** [comment]
> LGTM - tested on a Debian system successfuly

Thanks, getting closer to a release :)

**Pull request merged**
