### PR TITLE
about: Wrap about dialog in a scrolledwindow

### LINKED ISSUE #23: Min window hight value too high - window gets partially hidden behind keyboard
On a Librem 5, and I assume on a Pinephone as well the bottom part of the window along with all the buttons on the bottom bar get hidden behind the virtual keyboard.

### PR DESCRIPTION
**Pull request by tchx84**
Closes #23

### CODE REVIEW

**Comment by tchx84** [comment]
Merge after #25

**Comment by tchx84** [comment]
@allnamesaretakeningithub this should fix the issue, can you help me testing it?

**Comment by allnamesaretakeningithub** [comment]
> can you help me testing it?

@tchx84 gladly help you test this

**Comment by allnamesaretakeningithub** [comment]
@tchx84 just tested this branch and it looks good to me. Thanks for this fix!

**Comment by tchx84** [comment]
> @tchx84 just tested this PR and it looks good to me. Thanks for this fix!

Thanks for testing it! Now I need to deal with this rebase...

**Comment by tchx84** [comment]
Fixed in https://github.com/tchx84/Portfolio/commit/1cb7c0c9dec875aafe265cd269c9e1d5f071a7d5

**Pull request closed without merging**
