### PR TITLE
places: Support classic places

### LINKED ISSUE #120: A homepage
As a solution for a primary menu that begins to expand the number of options it incorporates, it may be a good idea to incorporate an homepage that allows to show the places and the connected storage devices

I've prepared this small mockup that can serve as a reference for the design of said page

portfolio-mockup

Navigation could occur in two ways:
1. Since Portfolio is currently replacing the content of the list presented to the user every time they navigate from one directory to another, there would be no conflict in using a HdyDeck with the following form:
   ```
   deck:
   ├── homepage
   ╰── directory list
   ```
   Allowing the user to return to the home page with a simple back gesture
2. Another solution could be to simply display a ubiquitous button that allows the user to return to the homepage at any time. This way could be useful if Portfolio at some point happens to use HdyDeck for navigating between directories instead of just changing the contents of the existing list

### PR DESCRIPTION
**Pull request by tchx84**
Closes #120

### CODE REVIEW

**Comment by tchx84** [comment]
Peek 2021-02-20 09-22

Based on your mockups, plus some creative freedom from my part :laughing: , and mixed it with some ideas from my conversation with @bertob and @exalm yesterday.

**Comment by bertob** [comment]
Seems a bit weird to have the places in a bounded listbox, but none of the other views. I'd do it either for both, or (probably better) in neither case.

Also, the navigation structure seems confusing. I would have expected the places view to open as the first thing when you open the app, and then always be at the bottom of the navigation stack. A shortcut to go back there in the bottom bar could make sense, but not even sure it's needed.

Also, would be nice to get rid of these huge symbolics. Can we just use the same hicolor icons as Nautilus?

**Comment by tchx84** [comment]
hey @bertob, thanks for the feedback.

> Seems a bit weird to have the places in a bounded listbox, but none of the other views. I'd do it either for both, or (probably better) in neither case.
> 

The properties view has the exact same layout.

image

> Also, the navigation structure seems confusing. I would have expected the places view to open as the first thing when you open the app.

@nahuelwexd suggested the same but, to me, when I open a file manager I expect to see files, otherwise feels disorienting.

I suppose we're seeing completely different navigation flows.

> and then always be at the bottom of the navigation stack. A shortcut to go back there in the bottom bar could make sense, but not even sure it's needed.
> 

I am not sure I understand the suggestion here. You mean that, If I wanted to jump to to Downloads folder (or a SD card) I would need to navigate "back"?

> Also, would be nice to get rid of these huge symbolics. Can we just use the same hicolor icons as Nautilus?

I know you suggested this before, but I think it gives Portfolio it ows identity, and kind of matches the minimalism theme as well.

**Comment by tchx84** [comment]
@bertob ok, I think I got the navigation part... (putting together some ideas from @nahuelwexd).

1. "places" is the starting point, and you can navigate all way back.

Peek 2021-02-21 08-40

2. and, you can "jump back" in one swipe (note that the animation makes this consistent).

Peek 2021-02-21 08-41

3. the "cost" is that, since navigation occurs at the bottom-right corner, I need to make that consistent in all pages.

Screenshot from 2021-02-21 08-37-33
Screenshot from 2021-02-21 08-37-05

**Comment by bertob** [comment]
> "places" is the starting point, and you can navigate all way back.

Nice, this makes a lot more sense to me!

> and, you can "jump back" in one swipe (note that the animation makes this consistent).

Not so sure about that, I would have expected swiping to always go back one level (and have matching animations), rather than having just one swipe going all the way back.

> the "cost" is that, since navigation occurs at the bottom-left corner, I need to make that consistent in all pages.

How so? What's the problem with keeping those back buttons in the top left?

**Comment by bertob** [comment]
> I know you suggested this before, but I think it gives Portfolio it ows identity, and kind of matches the minimalism theme as well. 

The problem is that these icons are not designed for the larger size, so they look weird. Perhaps you could use them at 16px but have a larger (32px or so) circle behind them.

**Comment by nahuelwexd** [comment]
> How so? What's the problem with keeping those back buttons in the top left?

Usability with one hand

**Comment by tchx84** [comment]
> Nice, this makes a lot more sense to me!

:heavy_check_mark: 

> Not so sure about that, I would have expected swiping to always go back one level (and have matching animations), rather than having just one swipe going all the way back.

That's the feature actually. A quick way to access these places and devices.

E,g. say you select and copy something, while being 7 sub folders deep from $HOME. If swipe-back moves only one level at a time, it would require 8 swipes (or worse, 8 button presses) to find that places/devices list again. With this, instead, you can reach that list in one action.

It is important to note that, when you move from the welcome page to the files page, there is an animation. There is no animation when you browse directories (back or forward). So that should help to show how the app is layered.

> How so? What's the problem with keeping those back buttons in the top left?

Well, two reasons:

1. While on the files page, when you exhaust all the "back" navigation it switches back to the welcome page, so it would be inconsistent to have the same action in a different place for the other two pages.
2. Some phones are a bit too big for my very average-sized hands and having the back button at the top-left corner forces you to use the secondary hand or to flex you current hand uncomfortably. Also, like @nahuelwexd mentioned, can't hurt to make it more accesible.
 
Moving these buttons there solves both issues, and is not like it's taking critical space either.

**Comment by bertob** [comment]
> E,g. say you select and copy something, while being 7 sub folders deep from $HOME. If swipe-back moves only one level at a time, it would require 8 swipes (or worse, 8 button presses) to find that places/devices list again. With this, instead, you can reach that list in one action.

Sure, but there are other (IMO nicer) ways to address that use case, for example with tabs, or just a shortcut button that takes you to the places view.

As for having the back button at the bottom:
1. We already do this in other apps (e.g. Web): persistent back/forward controls for content navigation, in-headerbar back buttons for generic app stuff (e.g. Preferences). I think it's much weirder to have a random bar with just a back button at the bottom on the About view than back buttons in different places across the app. 
2. Large-phone ergonomics is not really a problem since we have the back gesture and people can expect it to work across all apps.

**Comment by tchx84** [comment]
> Sure, but there are other (IMO nicer) ways to address that use case, for example with tabs, or just a shortcut button that takes you to the places view.
> 

Not sure we have much space left for tabs and I actually liked this idea because it avoids adding more buttons hehe.

The other issue, which is purely technical, is that the app is not really structured to navigate folders that way (it's literally one listview). Not saying it can't be done, but to do it right, it will need more time than I can afford now.

> As for having the back button at the bottom:
> 
> 1. We already do this in other apps (e.g. Web): persistent back/forward controls for content navigation, in-headerbar back buttons for generic app stuff (e.g. Preferences). I think it's much weirder to have a random bar with just a back button at the bottom on the About view than back buttons in different places across the app.

Alright, I will see how I can do some research on this, please share it with me if you do! I will revert these to the headerbar.

**Comment by bertob** [comment]
> Not sure we have much space left for tabs

I'd do something like we have in Web for that, with a single button in the bottom bar opening a separate tabs view. There's an adaptive tabs widget in the works that will give you that behavior more or less for free, so it's probably worth waiting for that to land in libhandy/adwaita :)

> I will revert these to the headerbar.

:+1:

**Comment by tchx84** [comment]
> > Not sure we have much space left for tabs
> 
> I'd do something like we have in Web for that, with a single button in the bottom bar opening a separate tabs view. There's an adaptive tabs widget in the works that will give you that behavior more or less for free, so it's probably worth waiting for that to land in libhandy/adwaita :)

Alright, will keep an eye on that.

> 
> > I will revert these to the headerbar.

**Pull request merged**
