### PR TITLE
Update all translations

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@Vistaus @cho2 @eson57 I probably got something wrong :rofl:  Please double check whenever possible.

**Comment by cho2** [comment]
@tchx84 https://github.com/tchx84/Portfolio/pull/89/commits/344d70f31cbaf66aa4940d21e43e7152f4b9d523 LGTM

**Comment by Vistaus** [comment]
Also LGTM

**Comment by eson57** [comment]
> I probably got something wrong.
Yup. ;)

**Pull request merged**
