### PR TITLE
about: Move it upwards and provide its own headerbar

### LINKED ISSUE #18: About dialog should have its own header bar
Currently when you swipe back from the About screen, the headerbar abruptly changes, which looks weird. Instead, the About screen should have its own headerbar with just the back button, "About" title, and window controls (no primary menu), which slides in/out along with the view itself.

### PR DESCRIPTION
**Pull request by tchx84**
Closes #18

### CODE REVIEW

**Comment by tchx84** [comment]
Merge after #24

**Comment by tchx84** [comment]
@bertob this is what you meant right?

Peek 2020-12-22 21-33

**Comment by bertob** [comment]
Yup, looks great!

**Comment by tchx84** [comment]
> Yup, looks great!

Thanks x2

**Pull request merged**
