### PR TITLE
devices: Ignore system devices

### LINKED ISSUE #245: properly handle already unlocked luks volumes
Running portfolio on my device, there's an entry for the luks partition that has my rootfs. Tapping on it prompts me for the passphrase to unlock it... but it's already unlocked. Perhaps portfolio should hide an encrypted volume if it's already unlocked and mounted to `/` ?

I'm not quite sure how it should be handled to be honest. This problem is mostly cosmetic, since I don't think I'd be able to actually unlock it through portfolio (since it's already unlocked, I think cryptsetup will complain), and it's unlikely that the 'eject' button would work too (I didn't try it... for obvious reasons... heh)

### PR DESCRIPTION
**Pull request by tchx84**
See http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-property-org-freedesktop-UDisks2-Block.HintSystem

Closes #245

### CODE REVIEW

**Comment by tchx84** [comment]
@craftyguy can you give this a try?

**Comment by craftyguy** [comment]
yes I will! 😄  sorry for the delayed response!

**Comment by craftyguy** [comment]
@tchx84 looks like we have a winner!

oKj7

**Comment by tchx84** [comment]
@craftyguy awesome, just to double check my tests:

1. Check if still detects any non-encrypted external devices.
2. Check if still detects any encrypted external devices.

**Comment by craftyguy** [comment]
> Check if still detects any non-encrypted external devices.

Yep!

> Check if still detects any encrypted external devices.

Yep!

Tested with an external usb-c drive directly connected to my librem 5.

**Comment by tchx84** [comment]
Thanks @craftyguy !

**Comment by craftyguy** [comment]
@tchx84 you're welcome! thank you for finding an elegant solution to this issue :D

**Pull request merged**
